### ISSUE TITLE
Archiving Branches

### ISSUE THREAD

**Issue by ivankruchkoff** [10up/Engineering-Best-Practices#185] opened 2017-03-16 14:38 UTC
Would like to start a discussion here as to whether this is relevant. Thoughts?

**Comment by ericmann** [comment] 2017-03-16 15:45
This pattern was added to the best practices documentation to massage away a few individual concerns about using version control that, frankly, no longer apply. If the team is properly trained on how VCS works (either Git or otherwise), "archived branches" is fundamentally unnecessary.

I say this as the original proponent of the practice. 👍  to removing the documentation as irrelevant.

**Comment by stevegrunwell** [comment] 2017-03-16 15:48
I'm all for removing it. Git tags are useful for versioned releases or major milestones (e.g. "rolled out the new theme", "launched this major feature", etc.) but archiving `fix/spelling` clutters the repository.

If not a complete removal, the archiving should be scoped to only those that would truly benefit from tagging.

**Comment by ivankruchkoff** [comment] 2017-03-16 16:06
There's some active discussion in the 10up slack, reasons where it can be useful:
1) Beanstalk takes a long time to load for a CR.
Proposed solution: delete unused branches.

2) An incomplete feature still exists, and we want to avoid an engineer accidentally deleting the branch.
Proposed solution: anyone with a local copy can still restore the branch, anyone who knows what to grok can still find the commit for the branch and restore it, or we can archive tag only those branches.

3) Audit purposes, I think this is very project specific and shouldn't influence the way all project repos operate.

I think the biggest benefit for tags are for your CI system to tag a release so that a rollback is easy to occur.

**Comment by tlovett1** [comment] 2017-04-10 21:47
@ericmann what were the original concerns? I never really understood this. Here are the branch scenarios that I see:

1. Engineer is working on branch. Branch stays.
2. Engineer started on a branch but decided the code change was unnecessary. Engineer deletes branch.
3. Engineer finished a branch and merged into staging/master. Engineer deletes branch. Anyone who wants to find the branch should be able to do so via the commit log since the branch was merged without fast forward.

Am I missing something?

**Comment by ericmann** [comment] 2017-04-10 22:26
The original concerns were relevant to a specific team working on a specific client project (which was, at the time, the only project actively using multiple feature branches at the same time). The practice of archive branches was designed specifically for that project and adopted more broadly as it was the "best solution we have right now."

The specific justification for it was due to branches needing to be merged into `master`/`trunk` in order to deploy to a VIP staging environment, where the feature was then reviewed for acceptance by non-technical stakeholders. Sometimes that review would happen quickly, sometimes it would take 3-4 months, over which time we'd start working on countless other branches. Archiving branches was a way to keep our branching model clean without losing references back to specific features if the stakeholders who requested the feature elected to pull the plug.

> Am I missing something?

Nope. Archiving branches was a somewhat contrived workflow designed to fit a team, project, and a time where not everyone involved fully groked version control or had proper visibility into how things were working with deployments. As I said above:

> If the team is properly trained on how VCS works (either Git or otherwise), "archived branches" is fundamentally unnecessary.

**Comment by ivankruchkoff** [comment] 2017-04-11 02:23
I put out a PR https://github.com/10up/Engineering-Best-Practices/pull/188 to remove the archive branches documentation, since based on this discussion, and the audit reason provided above, it's not something we SHOULD do for all branches, but rather selectively apply with discretion (e.g. unfinished branch / audit reasons)

**Comment by tlovett1** [comment] 2017-04-11 02:31
Thanks @ericmann and @ivankruchkoff !!

**Comment by ivankruchkoff** [comment] 2017-04-11 02:34
Merged and closed.

**Closed as completed** 2017-04-11 02:34 UTC
