### ISSUE TITLE
Do not commit compiled files

### ISSUE THREAD

**Issue by emeaguiar** [10up/Engineering-Best-Practices#121] opened 2015-12-11 22:25 UTC
We have been talking about this in the Front-End Engineers room. We should not commit compiled/minified css or js files to the repository. We could be using hooks to run grunt and compile them in the server. That way we will see a lot less of conflicts when committing.

I think we should add a section about this and start putting it into practice.

**Comment by nicholasio** [comment] 2015-12-11 23:39
+1 for this.

**Comment by tlovett1** [comment] 2015-12-14 20:06
I agree although this won't work for certain hosts i.e. managed WP hosts.

**Comment by morganestes** [comment] 2015-12-16 16:49
Although this is a commonly-accepted practice, as @tlovett1 mentioned it doesn't work for some hosts, and it is also a problem when using intermediaries who deploy on your behalf (hosted repos with only file access). Since each hosting environment is different, it's difficult to say "don't do this" without an example of what to do instead and for that to happen we're assuming much:
- You can deploy to a host that has Git hooks configured.
- Your server has Grunt, node, npm, Ruby, PHP-CLI, etc. installed and configured properly.
- Your user has the correct permissions to run the tasks to build the assets.
- File-level caching is enabled during the build process and you can easily bust cache when new assets are available.
- Insert any other system-wide configs you can think of.

It may be prudent to talk about problems caused by committing production-ready assets to a repo (and "we will see a lot less of conflicts when committing" is an excellent reason), but I hesitate to include it without a list of caveats to consider before moving to a fully-non-compiled repo workflow.

**Comment by jonathantneal** [comment] 2015-12-16 17:38
As we discuss the pros and cons, I want to bring up the idea of allowing _uncontrolled_ hosts to work off **orphan** branches. This would mean uncontrolled hosts should not run from master, and in our case staging under 10uplabs.

Also, my two cents. The general preference should be ”source control is for the source code and not for the compiled code.”

**Comment by benoitchantre** [comment] 2016-01-14 08:55
> I agree although this won't work for certain hosts i.e. managed WP hosts.

Same thing for shared hosting.

I think the answer depends on how you will deploy the theme / plugin (sftp, git pull, plugin like GitHub Updater, third service like WP Pusher, etc.).

A section about private theme / plugin deployment could be a good addition. There could be different workflows depending on the server capabilities. Good practices / requirements already exist for [public  theme](https://make.wordpress.org/themes/handbook/review/required/#stylesheets-and-scripts) / plugin hosted on wordpress.org.

**Comment by tlovett1** [comment] 2017-01-30 01:22
I think this should be mentioned as a best practice with the caveat that it isn't worth pursuing on certain managed hosts.

**Comment by nprasath002** [comment] 2018-01-03 05:43
This already merged with https://github.com/10up/Engineering-Best-Practices/commit/15ba91d7c6a353e158ccc4d2c9e9cc63f8c71bfd. Closing this now

**Closed as completed by nprasath002** 2018-01-03 05:43 UTC
Labels: Enhancement
